# Generated by Django 3.1.4 on 2020-12-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201202_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbourhood_logo',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='occupants_count',
        ),
    ]
