# Generated by Django 3.1.4 on 2020-12-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201203_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
