# Generated by Django 3.1.4 on 2020-12-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
