# Generated by Django 3.1.4 on 2020-12-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
